### ISSUE TITLE
期望可以本地跑效果

### ISSUE THREAD

**Issue by cloudyan** [perfsee/perfsee#105]
目前只能 github 导入项目，期望开放本地创建项目

<img width="407" alt="image" src="https://user-images.githubusercontent.com/912821/191790176-7465d47b-70bd-413b-ab0b-33158d94839e.png">

作为性能分析平台，期望能先本地跑服务，并能验证各项功能，这样才方便推广到团队项目接入进去

**Comment by flycj** [comment]
同问

**Comment by forehalo** [comment]
With #126 landed, you can now easily create local project with `any` host

<img width="666" alt="image" src="https://user-images.githubusercontent.com/8281226/200534478-9f6d1134-669e-434f-8184-eb56638bcb4f.png">
