### ISSUE TITLE
Cannot run in no-git env

### ISSUE THREAD

**Issue by moonrailgun** [perfsee/perfsee#163]
Because of this code:

```
export const BUILD_ENV: BuildEnv = {
  isCi: envs.isCi,
  pwd: 'root' in envs && envs.root ? envs.root : process.cwd(),
  platform: process.env.PERFSEE_PLATFORM_HOST ?? 'https://perfsee.com',
  upload: !process.env.PERFSEE_NO_UPLOAD && envs.isCi,
  git: gitEnvPromise.then((gitEnv) => (gitEnv ? Promise.resolve(gitEnv) : getGitEnv())),
}
```

in init, will call `getGitEnv` and fetch git context, but its not good in some no-git environment for example: `vercel deploy`.

Maybe we should get this variable when we use it?

**Comment by moonrailgun** [comment]
or add a catch block if not get git environment..

**Comment by EYHN** [comment]
Because we need to read information such as commits, branches, tags, etc. from git, this information is necessary for uploading artifacts.

The vercel build environment provides a series of system environment variables, perhaps we can use the information. https://vercel.com/docs/concepts/projects/environment-variables#system-environment-variables

**Comment by moonrailgun** [comment]
> Because we need to read information such as commits, branches, tags, etc. from git, this information is necessary for uploading artifacts.
> 
> The vercel build environment provides a series of system environment variables, perhaps we can use the information. https://vercel.com/docs/concepts/projects/environment-variables#system-environment-variables

My scene is deploy with cli command  `vercel deploy`, not github app.

And in some case we not need it in init.

I resolve it with require:

```ts
if (PREF_REPORT) {
  const PerfseePlugin = require('@perfsee/webpack').PerfseePlugin;
  plugins.push(
    new PerfseePlugin({
      project: 'xxxxxxx',
    })
  );
}
```

but will lose type.

![image](https://user-images.githubusercontent.com/6964737/197444885-1c69f5d7-0626-435f-bf64-017e678d8354.png)

-----------

I claim this issue because in esm, standard import is `import xxx from 'xxx'` or `import('xxx').then(...)`, no way to sync import module(i know i am in node runtime, just hate use `require` in typescript)

**Comment by forehalo** [comment]
Thanks for you remind, and we definitely should avoid reading required information & computing during lib importing. We will work on it and solve this issue asap.

**Comment by Brooooooklyn** [comment]
This works on Vercel https://github.com/perfsee/perfsee/commit/81d012fa10df292279d41f8ddd64858f7218a64b
