### ISSUE TITLE
Bundle overview pie chart looks like a little weird when hover status

### ISSUE THREAD

**Issue by moonrailgun** [perfsee/perfsee#182]
![image](https://user-images.githubusercontent.com/6964737/199639723-45da547e-96f9-469a-9c15-d956026ad24c.png)

**Comment by forehalo** [comment]
@moonrailgun I can't reproduce this issue so if you have a link or a way to reproduce it would be better.

**Comment by moonrailgun** [comment]
I make my repo public but its looks like still must be login, can you look this page?
https://perfsee.com/projects/tailchat/bundle/12

**Comment by EYHN** [comment]
@moonrailgun  Yes, we can access this link and everyone can view your project once it is public, but login is required.

And i'm looking into this issue.

**Comment by moonrailgun** [comment]
> @moonrailgun Yes, we can access this link and everyone can view your project once it is public, but login is required.
> 
> And i'm looking into this issue.

Well, is any plan for more friendly public view experience optimization? For other CI platform, public report dont need login.

And thanks for your reply
