### ISSUE TITLE
[Bug] can't login to the platform 

### ISSUE THREAD

**Issue by promer94** [perfsee/perfsee#241]
https://user-images.githubusercontent.com/15878786/211160127-b540cd4e-d5bc-4c0e-a060-58820ead207f.mp4

![CleanShot 2023-01-07 at 00 39 49@2x](https://user-images.githubusercontent.com/15878786/211160117-0f541089-697a-4651-935d-05cf4602b2a7.png)

**Comment by forehalo** [comment]
fixed in [#207](https://github.com/perfsee/perfsee/pull/217/files#diff-6588d1939d4845f2285863beb5b29314960e906b3447e3cdecccfda600180bffR157)

please wait for the next release
