### ISSUE TITLE
No provider for GraphQLClient

### ISSUE THREAD

**Issue by Kingwl** [perfsee/perfsee#278]
<img width="903" alt="image" src="https://user-images.githubusercontent.com/6831019/217520230-3989e4cf-35f8-4917-8e94-eda96015c7a0.png">

<img width="863" alt="image" src="https://user-images.githubusercontent.com/6831019/217519954-61cfeb5f-723a-4d17-a548-66f11d4a7618.png">

**Comment by forehalo** [comment]
occurs after [bumping dependencies ](https://perfsee.com/projects/perfsee/bundle/568)
