### ISSUE TITLE
Error: Cannot find module '@perfsee/bundle-analyzer/types'

### ISSUE THREAD

**Issue by Kingwl** [perfsee/perfsee#285]
```
yarn build
node ./packages/platform-server/dist/index.js
```

Output:
```
node:internal/modules/cjs/loader:936
  throw err;
  ^

Error: Cannot find module '@perfsee/bundle-analyzer/types'
```

**Comment by forehalo** [comment]
`node -r ./tools/paths-register ./packages/platform-server/dist/index.js`

**Comment by Kingwl** [comment]
Might just add a task like: "start:prod": "node -r ./tools/paths-register ./packages/platform-server/dist/index.js" ?

**Comment by forehalo** [comment]
> Might just add a task like: "start:prod": "node -r ./tools/paths-register ./packages/platform-server/dist/index.js" ?

noted
