### ISSUE TITLE
Compare layout should works fine

### ISSUE THREAD

**Issue by Kingwl** [perfsee/perfsee#288]
<img width="1591" alt="image" src="https://user-images.githubusercontent.com/6831019/218024809-cab06136-f0a6-4fd1-b162-23690d95ce49.png">

```patch
 .css-1cw82dn-BuildHistoryItem {
     overflow: hidden;
     flex: 1 0 100%;
+    flex-shrink: 1;
 }
```

<img width="1179" alt="image" src="https://user-images.githubusercontent.com/6831019/218025281-f6aeeb33-fc33-4c50-8c69-c4a2c8f0aa7f.png">

**Comment by forehalo** [comment]
resolved in #308
