### ISSUE TITLE
The size of the other files seems to be double-counted by multiple entry points

### ISSUE THREAD

**Issue by Kingwl** [perfsee/perfsee#299]
<img width="1181" alt="image" src="https://user-images.githubusercontent.com/6831019/218444776-3f4762a1-33ef-472e-b364-aef1b591b33a.png">
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/6831019/218444824-29e6a2a2-4640-4ec3-a3ad-8173ac839f3d.png">

**Comment by forehalo** [comment]
does your polyfills entry accidentally request such assets in some code paths?

**Comment by Kingwl** [comment]
Nope. Pure polyfills as the name said.

**Comment by Kingwl** [comment]
There's only `corejs/*` and `regenerator/runtime` in the polyfills entry points. Using vite.

**Comment by Kingwl** [comment]
<img width="679" alt="image" src="https://user-images.githubusercontent.com/6831019/219629345-cba73888-4668-4021-9be9-5d3203e16f1a.png">
Not sure why union all assetsEntries for every entry point. Any reason?

**Comment by forehalo** [comment]
@DomonJi it's caused by rollup metafile miss transforming

**Comment by DomonJi** [comment]
@Kingwl @forehalo 
Because we can't tell which entrypoint is a asset file belongs to.
The rollup mefatile does not provide enough informations.

e.g.
![Image](https://user-images.githubusercontent.com/9986655/221767736-1cb6d6c6-cc88-4326-8d9f-2211de5f1241.png)

**Comment by Kingwl** [comment]
Might collect these relationship before outputBundle?
