### ISSUE TITLE
Make good use of the event system to do before/after logic hooks

### ISSUE THREAD

**Issue by forehalo** [perfsee/perfsee#333]
## What is hooks?

We always need to do some extra work after one important thing done, like we may send notification to let users be aware of the progress of analysis jobs,  call users' predefined webhooks, do some pending updates and so on.

If we mix all such "pending logic" with the core thing a controller/resolver really do,  the logic complexity will significantly increase so that the maintainability will be affected as well.

When we were designing the webhook system, we kept in mind that the hooks are actually kind of events, instead of being received by local consumers but the ones behind the url users provided.  In this way, we implemented the webhook calling by event system without any doubt.

```jsx
// job update logic
async receiveBundleAnalysisUpdate(updates) {
  const savedBundle = await Bundle.save(updates)
  this.event.emit(`bundle.update.${savedBundle.status}`, savedBundle)
}

// hooks
@OnEvent(`bundle.update.${BundleStatus.Created}`)
bundleCreatedHook(bundle) {
  // calling the hook
}

@OnEvent(`bundle.update.${BundleStatus.Done}`)
bundleDoneHook(bundle) {
  // calling the hook
}
```

## What about before?

But this didn’t happened in before:

```jsx
async receiveBundleAnalysisUpdate(updates) {
  const savedBundle = await Bundle.save(updates)

  if (savedBundle.status === BundleStatus.Done) {
    this.notification.sendBundleNotification({
      // construct required fields
    })
  }
}
```

in the example above, `receiveBundleAnalysisUpdate` firstly dumps the updates to db. Furthermore, it checks whether the final status is `Done` to determine whether a notification should be send, then send the notification with required options if the test passes. 

That’s so bad because the business logic totally gets involved with extra works, and all the detail of callees also get exposed to the business. What if the notification send method add a new required option? Both notification and bundle services required to be updated, but the whole thing is just about the notification itself.

## Hooks are broadcasts

Since we’ve already implemented webhooks in our event system with fully typecheck support, it won’t be a hard thing to migrate all hook like code to event as well.

```jsx
// job update logic
async receiveBundleAnalysisUpdate(updates) {
  const savedBundle = await Bundle.save(updates)
  this.event.emit(`bundle.update.${savedBundle.status}`, savedBundle)
}

// Hooks
@OnEvent(`bundle.update.${BundleStatus.Created}`)
bundleCreatedHook(bundle) {
  // calling the hook
}

@OnEvent(`bundle.update.${BundleStatus.Done}`)
bundleDoneHook(bundle) {
  // calling the hook
}

// Hook-like
@OnEvent(`bundle.update.${BundleStatus.Done}`)
bundleDoneNotification(bundle) {
  // send notification
}
```

Now, everything is clear.

**Comment by lizimeow** [comment]
more details please
