### ISSUE TITLE
package.json includes workspace:*

### ISSUE THREAD

**Issue by fz6m** [perfsee/perfsee#86]
这个包没发好呀，用不了。

<img src='https://user-images.githubusercontent.com/59400654/190851685-01c7ef41-1f17-4f8d-8f20-9f1b650e4bc4.png' width='400' />

See https://registry.npmjs.com/@perfsee/webpack

**Comment by forehalo** [comment]
fixed in `1.0.0-alpha.3` packages, you may want to reinstall the plugin by `yarn add @perfsee/webpack@latest`
